// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeiculosAPI.Entities;

namespace VeiculosAPI.Migrations
{
    [DbContext(typeof(VeiculosContext))]
    [Migration("20201124200859_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseSerialColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VeiculosAPI.Entities.Caminhao", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseSerialColumn();

                    b.Property<string>("cor")
                        .HasColumnType("text");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("placa")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Caminhao");
                });

            modelBuilder.Entity("VeiculosAPI.Entities.Carro", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseSerialColumn();

                    b.Property<string>("cor")
                        .HasColumnType("text");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("placa")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("VeiculosAPI.Entities.Moto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseSerialColumn();

                    b.Property<string>("cor")
                        .HasColumnType("text");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("placa")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Moto");
                });
#pragma warning restore 612, 618
        }
    }
}
